select_origin: directory
files_origin: ./
nodes_origin: null
links_origin: null
nodes_online: null
links_online: null
images_origin: null
export_target: ../../temp
history: false
focus_max: 2
record_types:
  undefined:
    stroke: "#000"
    fill: "#000"
link_types:
  undefined:
    stroke: simple
    color: "#000"
references_as_nodes: true
references_type_label: "reference"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 7
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 10
attraction_force: 600
attraction_distance_max: 600
attraction_vertical: 0
attraction_horizontal: 0
hide_id_from_record_header: true
views: {}
record_metas:
  - pays
title: "Cosma demo: timeline"
author: null
description: null
keywords: []
link_symbol: null
link_context: inline
csl: null
bibliography: null
csl_locale: null
css_custom: null
devtools: false
lang: fr
generate_id: never