name: Bug report
description: Unexpected behaviour, bugs, glitches and other issues
title: "[Bug] "
labels: [bug]

body:

  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to report issues with Cosma. 
        Please be as accurate as possible when describing the issue.
        If you have encountered several bugs, please create a new issue for each one.

  - type: textarea
    id: action-before-bug
    attributes:
      label: Actions leading to the bug
      description: >
        Please describe the actions that led to the bug.
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug description
      description: >
        Which expected behaviour failed, or which unexpected behaviour occured?
    validations:
      required: true

  - type: checkboxes
    id: os
    attributes:
      label: What is your operating system?
      description: >
        Please select the OS on which you observed the bug.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: What version of the operating system are you on?
      description: >
        Please indicate the OS version to improve our understanding of the bug.
      placeholder: "Big Sur 11.4, Windows 10…"
    validations:
      required: true

  - type: textarea
    id: more
    attributes:
      label: Additional information
      description: >
        Please add any other relevant information to help us fix the issue.
    validations:
      required: false

  - type: markdown
    id: out
    attributes:
      value: |
        We are a small team with intermittent funding.
        The issue may not be fixed before some time.
        Thank you for your patience and for using Cosma!
